### ISSUE TITLE
P values >0.05 not being filtered

### ISSUE THREAD

**Issue by GBeattie** [Teichlab/cellphonedb#134]
Hey,

Great application, I'm just worried that many of the interactions in my results files have P values over 0.05 for all cluster-cluster comparisons (I've used the default statistical pipeline).

Why might this be the case? Also, could you outline the parameters an interaction needs to meet before being included in the output (the high P value interactions don't necessarily have high mean values, so the cutoffs used don't seem intuitive).

Thank you for any information!

**Comment by mief** [comment]
Hi,

It is actually the other way around, low p-values would have high means. However, since our statistics checks for specificity or enrichment of interactions between two cell types, then you would get low p-values (high specificity) for interactions with high mean between those two cell types, but lower means across the other cell types. Another parameter is the threshold of percentage of cells expressing the specific ligand/receptor which by default is 10%, but you can play around with this.

I hope this helps.

Best,
Mirjana
