### ISSUE TITLE
p-values still with 2 decimal places after --result-precision 4

### ISSUE THREAD

**Issue by Dzhan4** [Teichlab/cellphonedb#150]
Hello,

Thank you for this great package! I just had an ongoing issue with precision of p-values. Even after I set --result-precision 4 to achieve 4 decimal places, I still get p-values of 1, 0.9, 0.5, 0, etc without anything inbetween. For the time being I'm assuming anything with 0 was rounded down and therefore less than 0.05, but it certainly makes the very significant p-values harder to discern.

I'm using the following code:
`cellphonedb method statistical_analysis meta.txt count.txt --iterations=10 --threads=1 --result-precision 4`

Any tips?

**Comment by mief** [comment]
Hi,
Thanks for the nice words! With 10 iterations, you will only get one decimal, because the p-value is computed as the proportion of the “permuted” means (which in your case will be 10) which are as or higher than the actual mean. The 0s are because in many cases, the actual mean is higher than all values. So I would suggest using 1000 permutations, in which case you will get up to 3 decimals. 
I hope this helps.
Best,
Mirjana
