### ISSUE TITLE
cellphonedb hestmap error

### ISSUE THREAD

**Issue by khandaud15** [Teichlab/cellphonedb#169]
Hi, thanks for developing such a nice tools. I am currently using it for scrnaseq datatset. I ran statistical analysis with the metadata file and count file. I got the outputs for that , but when I am trying to make the heatmap plot for the results. I am getting an weird error. I am using the same metadata file which i used to running statistical analyisis. can you please help me with an issue 

Error in `[.data.frame`(all_intr, , pairs1[i]) : 
  undefined columns selected

I am using this cammand
cellphonedb plot heatmap_plot  scrna-meta.txt --pvalues-path pvalues.txt --output-path CellPhoenDb-output --count-name heatmap_count.pdf 

my metadata has 2 columns like you mentioned

Thanks in advance

**Comment by weiiioyo** [comment]
Hi, I met the same issue. Have you solved it?

**Comment by Sa753** [comment]
Hi I am getting the same error

Error in `[.data.frame`(all_intr, , pairs1[I])
undefined column selected

Any suggestions please?

**Comment by berixD** [comment]
I could solved the error by updating my meta.data file. Due to subsampling, some celltypes were not present in my pvalue file. So, I removed these celltypes from my meta.data file in order to plot the heatmap. 
The error ocurred in line33:
n1 = intr_pairs[which(all_intr[,pairs1[i]]<=pvalue)]

object pairs is derived form the metadata file and all_intr is derived from the pvalue file. 
The subsampling issue may also explain why the error is not easily reproducible.
