### ISSUE TITLE
'user custom interactions' that do not exist in public repositories

### ISSUE THREAD

**Issue by wzhao01** [Teichlab/cellphonedb#170]
Dear cellphonedb team,

Thank you for developing this valuable tool!

I have been following the tutorial: https://github.com/Teichlab/cellphonedb#generating-user-specific-custom-database

However, I was wondering how I may create a custom database of 'user custom interactions' that doesn't yet exist in any public repository. I only have protein names for the predicted interacting pairs, without a proper 'id_cp_interaction', 'annotation_strategy', 'source', 'partner_a', or 'partner_b'. I do not know if the names for these columns must follow some specific format requirement, or if they must already be in the cellphonedb database.

Thank you again!

**Comment by mief** [comment]
Hi,

Thank you for your interest in our tool!

Partner_a and partner_b need to be either uniprot ids or complex names of the two interacting proteins. If you have the names, you can find their uniprot ids from uniprot. You can put anything you want in the id_cp_interaction field, source and annotation strategy, the field are mandatory because we only consider curated interactions for the analysis and it is important to know the source, but for your own database, you can choose how to fill in those fields. Once you generate the new database, the annotation_strategy will be called 'user_curated'.

I hope this helps,
Mirjana
