### ISSUE TITLE
Interpreting lack of enrichment of ligand-receptor pair

### ISSUE THREAD

**Issue by ryland-mortlock** [Teichlab/cellphonedb#182]
Hello, I have a conceptual question building off of several threads here discussing running CellPhoneDB on different groups. 

I have implemented the same as what is mentioned by the askers and the developers, which is to run the pipeline separately for my two different conditions. The ligand-receptor pairs that are found to be enriched in both can obviously be compared in terms of their mean interaction value and the p-value. 

I am definitely interested in the pairs that were enriched under one condition but not the other. However, I am having difficulty interpreting this.  Especially since I have an interaction we are particularly interested in, where the expression values of both genes are very similar across the different clusters under both conditions. But the interaction only comes up as significant under one condition and not the other.

To be more specific, I notice that in the out files for CellPhoneDB, there are interactions which are in the out-file but have no significant enrichment scores between any cell types. Why did those ligand-receptor pairs make it into the final dataset but not others? Which filtering step actually removes the ligand-receptor pair from the results?

Any help is appreciated. Thanks so much!

**Comment by aditisk** [comment]
Hi @ryland-mortlock, did you figure this out ? I'm curious to know what the outcome is since I have a similar question for a project I am working on. Thanks.

**Comment by ryland-mortlock** [comment]
> Hi @ryland-mortlock, did you figure this out ? I'm curious to know what the outcome is since I have a similar question for a project I am working on. Thanks.

Nothing so far.

**Comment by mief** [comment]
Hi,
Many apologies for the late response. Please free to email me if you haven't received a response.
We only filter the receptors/ligands that are not expressed at all. They can still be not significant or not pass the threshold and still included in the final result. Here is how we filter:
        - Duplicated ensembl: Keep the first.
        - If ensembl is not in CellPhoneDB interactions.
        - Empty counts: Remove counts if all row values are 0.
        - Interactions without two components in counts.
        - Orphan ensembls: if the ensembl is only on one interaction component

For your specific example, the specificity of interactions between two cell types depends on all other cells. So it can happen that an interaction is enriched in one condition whereas not in another even the ligand/receptor are expressed in both, because it could be that in one case, the receptor/ligand was very specific for those cell types, but they are expressed in many cell types in the other condition. If you would like to look just based on expression, I would suggest using the normal mode and filter based on a threshold.

I hope this helps,
Mirjana
