### ISSUE TITLE
Question about plotting

### ISSUE THREAD

**Issue by evenDDDDD** [Teichlab/cellphonedb#198]
Hello, CellPhoneDB is a great software.
I have a small problem when I use mean.txt and pvalue.txt to draw pictures. This is my code and error:

`cellphonedb plot dot_plot --means-path ./out/means.txt --pvalues-path ./out/pvalues.txt --output-path ./out_plot`

`./lib/python3.6/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.cluster.k_means_ module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.cluster. Anything that cannot be imported from sklearn.cluster is now part of the private API.
  warnings.warn(message, FutureWarning)
[ ][APP][09/08/20-15:02:43][ERROR] Unexpected error
Traceback (most recent call last):
  File "./lib/python3.6/site-packages/cellphonedb/src/api_endpoints/terminal_api/plot_terminal_api_endpoints/plot_terminal_commands.py", line 38, in dot_plot
    columns=columns)
  File "./lib/python3.6/site-packages/cellphonedb/src/plotters/r_plotter.py", line 35, in wrapper
    from rpy2.rinterface_lib.embedded import RRuntimeError
  File "./lib/python3.6/site-packages/rpy2/rinterface_lib/embedded.py", line 7, in <module>
    from . import openrlib
  File "./lib/python3.6/site-packages/rpy2/rinterface_lib/openrlib.py", line 21, in <module>
    rlib = _dlopen_rlib(R_HOME)
  File "./lib/python3.6/site-packages/rpy2/rinterface_lib/openrlib.py", line 17, in _dlopen_rlib
    rlib = ffi.dlopen(lib_path)
OSError: cannot load library '/opt/R-3.6.1/lib/libR.so': /opt/R-3.6.1/lib/libR.so: cannot open shared object file: No such file or directory
`
I don’t know why this problem occurred, I installed the latest version of cellphonedb and R v3.6.3.
Expect a reply! Thank you!

**Comment by YZYwoazzzzz** [comment]
Hi,
Do you solve this problem, any ideas?
I also meet this problem.
thx

**Comment by beemilmlo** [comment]
Hello,
I am also wondering how to fix this. Have you made any progress?

Thanks,
RL

**Comment by YZYwoazzzzz** [comment]
please check your count matirx发自我的华为手机-------- 原始邮件 --------发件人： beemilmlo <notifications@github.com>日期： 2020年10月6日周二 晚上9:34收件人： Teichlab/cellphonedb <cellphonedb@noreply.github.com>抄送： YZYwoazzzzz <424463870@qq.com>, Comment <comment@noreply.github.com>主    题： Re: [Teichlab/cellphonedb] Question about plotting (#198)
Hello,
I am also wondering how to fix this. Have you made any progress?
Thanks,
RL

**Comment by prete** [comment]
Hi @evenDDDDD  @YZYwoazzzzz  @arielyh this most likely caused by `rpy2` looking for the shared object in the wrong place or your `LD_LIBRARY_PATH` not being set correctly. See https://github.com/rpy2/rpy2/issues/675

You can create a conda environment instead of using virtualenv and that will include R and all it dependencis. Follow the instructions on how to [create a conda environment from this comment](https://github.com/Teichlab/cellphonedb/issues/270#issuecomment-785355935).

Alternatively, if you can't create a new conda env you can try running the plotting scripts manually as [described here](https://github.com/Teichlab/cellphonedb/issues/286#issuecomment-822349683).
