### ISSUE TITLE
Output result: receiving and sending cell

### ISSUE THREAD

**Issue by m21camby** [Teichlab/cellphonedb#209]
Hi,

I have a question regarding output result. All output files come with column of each pair of cell type. I wonder which cell is ligand sending cell and which is receptor cell from divide by | ? 

e.g. 
If interacting pair is DSG2_DSC3 and I check the value in the column T-cell | B-cell. In this case, does T-cell express DSG2 and B-cell express DSC3? or other way around? 

Thank you in advance.

**Comment by akramdi** [comment]
Hi, 

From the nature protocol paper: 

"Importantly, interactions are not symmetric. In other words, when testing a ligand–receptor pair A_B between clusters X_Y, the expression of partner A is considered within the first cluster (X), and the expression of partner B within the second cluster (Y). Therefore, X_Y and Y_X represent different comparisons and will have different P values and means."

Hope it helps,

**Comment by mief** [comment]
Yes, this is true, thanks for the comment. In the specific case the T cell expresses GSG2 and the B cell cluster DSC3. 
In terms of sender/receiver, we didn't include directionality because in addition to ligand-receptor, we also include receptor-receptor interactions. But in the tables that can be downloaded from our website, we include information for each protein, whether it's a receptor or not, and for some of the secreted ligands, whether they are cytokines, hormones or growth factors.
