### ISSUE TITLE
Cellphonedb for integrated datasets

### ISSUE THREAD

**Issue by bapoorva** [Teichlab/cellphonedb#213]
Hi,

I have an integrated dataset with a control and a mutated sample of the lung. Following integration, I subsetted out the clusters of interest and reclustered them. Now i'm interested in finding the ligand receptor interaction between very specific cell groups. From your documentation, i can see we have to use normalized counts. But would it be appropriate to use the data from the integrated assay ? This is my code

```
scrna = readRDS("~/singlecelldata.RDS")
counts = as.data.frame(as.matrix(scrna@assays$integrated@data)) %>% rownames_to_column() %>% rename('Gene'='rowname')
```

**Comment by mief** [comment]
Hi,
If this is batch corrected data, then this shouldn't be used, it would be best to use the uncorrected normalised data. In the same way as this corrected data shouldn't be used for DE analysis, because the integration introduces dependencies between data points that would violate the assumptions of these statistical tests.
One suggestion for your control and mutated samples would be to run the method separately on the two conditions and compare the results.

**Comment by Emma1997WTT** [comment]
> Hi, If this is batch corrected data, then this shouldn't be used, it would be best to use the uncorrected normalised data. In the same way as this corrected data shouldn't be used for DE analysis, because the integration introduces dependencies between data points that would violate the assumptions of these statistical tests. One suggestion for your control and mutated samples would be to run the method separately on the two conditions and compare the results.

Hello, I have a question about this. One step in the principle of CellPhoneDB is to disrupt the ligand or the receptor label to calculate the average expression value. If the data before the batch is used to calculate, how to solve the problem of different sequencing depths?
