### ISSUE TITLE
About the communication direction

### ISSUE THREAD

**Issue by yewero** [Teichlab/cellphonedb#214]
In the `pvalues.txt` file, if the "receptor_a" is `True` and "receptor_b" is `False`, as follows:
| interacting_pair | gene_a | gene_b | receptor_a | receptor_b | X cell\|Y cell|
|----|----|----|----|----|----|
| A_B | A | B | True | False | 0 |

Does this mean that X cell is the **sending cell** which could express the **receptor gene** A? I am confused about that.

**Comment by mief** [comment]
Hi,
In addition to ligand-receptor interactions, we include also receptor-receptor interactions and that's why we did not include any directionality of the interactions. However, like you said, we included the information whether a protein is a receptor, so in this case you can use that to detect the sending/receiving cell. To help with this, we included additional information about some of the ligands in the 'secreted_desc' field, whether they are cytokines, growth factors or hormones.

**Comment by yewero** [comment]
I think the script above could solve this problem.

**Comment by yewero** [comment]
This script could simply fix the order of gene pairs in the output: https://github.com/Teichlab/cellphonedb/pull/218

**Comment by lixin4306ren** [comment]
Hi, @yewero 

In some cases, `receptor_a` and `receptor_b` are both `FALSE`, how do you determine the direction in these situations? Thanks.

Xin

**Comment by yewero** [comment]
@lixin4306ren The script `fixOrder.py` will only change the order from receptor/ligand to ligand/receptor. For the cases where `receptor_a` and `receptor_b` are both `FALSE`,  the order will not be changed.
