### ISSUE TITLE
sqlite3.OperationalError: database is locked 

### ISSUE THREAD

**Issue by wtj505531480** [Teichlab/cellphonedb#256]
![image](https://user-images.githubusercontent.com/26889995/105120144-a9b6d980-5b0c-11eb-82de-d749a0fc5d8e.png)

**Comment by prete** [comment]
Hi @wtj505531480 this issue happens when either the database is open (being read) by another tool at the same time (i.e. SQLite Browser) or the process crashes while writing to the db. The fix for the first one is easy, just close the program or process that's using it before running CellPhoneDB. For the second one, it may be easier to just re-download the database using `cellphonedb database download` or manually from the repository.
