### ISSUE TITLE
How to use environment.yaml install CellphoneDB environment in conda  

### ISSUE THREAD

**Issue by yuyzw** [Teichlab/cellphonedb#270]
How to use environment.yaml install CellphoneDB environment in conda  ?

**Comment by prete** [comment]
Hi @yuyzw! You can use this [environment.yml](https://github.com/Teichlab/cellphonedb/files/6038676/environment.yml.txt) _(you'll need to rename it from `environment.yml.txt` to `environment.yml` because GitHub does not allow yml files to be attached)_

Then, to create the environment use `conda env create -f cellphonedb.environment.yml`

Finally use `conda activate cpdb` to activate your environment and you'll have all that you need to run your analysis.
