### ISSUE TITLE
pandas.errors.ParserError in database generate

### ISSUE THREAD

**Issue by jariwalask** [Teichlab/cellphonedb#285]
I'm getting a `pandas.errors.ParserError: Too many columns specified: expected 4 and found 1` when running `cellphonedb database generate  --fetch`.

I also have a message `Could not fetch remote source MatrixDB, using available backup`, but that does not seem to be critical failing point.

Attached log file from the `cellphonedb database generate  --fetch` run.
[cellphonedb_generate.txt](https://github.com/Teichlab/cellphonedb/files/6113154/cellphonedb_generate.txt)

I've recently (2021-03-08) installed cellphonedb.
Any suggested solutions or how to debug this?

**Comment by prete** [comment]
Hi @jariwalask from the log I think `I2D` was the source that failed for you. 
Sometimes pulling the data from original sources fails (because the source throws an error), am error is returned instead of data and CellPhoneDB fails to parse that thinking that's real data. This is usually temporary and the original source starts working the next day or short after. 

I've tried generating the DB today and I did not get that error. Could you try again, please?

**Comment by prete** [comment]
Hi @jariwalask any updates on this? Were you able to generate the database?

**Comment by jariwalask** [comment]
Hi @prete,
I have additional issue due to proxy on my end. You can go ahead and close this issue ... I'll re-open if I'm still facing issues in generating the database.
Thanks

**Comment by jariwalask** [comment]
Hi @prete , would it be possible to update the db on the repo (maybe even on a quarterly basis) so folks facing similar issue can simply pull it from the repo?
Thanks
