### ISSUE TITLE
labels shown by string encoding

### ISSUE THREAD

**Issue by yjgeno** [Teichlab/cellphonedb#301]
Hi there, thanks for your package, excellent work!

I followed your guidebook and plot the heatmap using your example dataset. It turns out the labels show in their encoding instead of string:
![image](https://user-images.githubusercontent.com/77600778/115463783-d5bc2680-a1f1-11eb-9d86-8e42d21e81df.png)

Any thought about this issue? Thank you in advance!

**Comment by prete** [comment]
Hi @yjgeno indeed `41 44 52 42 32 5F 56 45 47 46 42` represents `ADRB2_VEGFB`. 
This may be caused by your system's encoding. Could you please inform your Operating System, CellphoneDB version and R version? and also, just to check, the example dataset you used are the files in [in/example_data](https://github.com/Teichlab/cellphonedb/tree/master/in/example_data)?

**Comment by prete** [comment]
also, is that from PDF output? do you face the same error when using [PNG or JPEG formats](https://github.com/Teichlab/cellphonedb#dot_plot)?

**Comment by yjgeno** [comment]
Hi, thanks for your comment. Yes, this happened across all the format (PDF, PNG, and JPEG)

OS: "Red Hat Enterprise Linux Server 7.1 (Maipo)"
R version 3.6.1
Python 3.7.10 
cellphonedb 2.1.7

**Comment by prete** [comment]
Hi @yjgeno could you try running the plotting scripts manually as described [here](https://github.com/Teichlab/cellphonedb/issues/286#issuecomment-822349683) to rule out `rpy2` being the culprit?

If that fails, perhaps changing the script to your encoding or wrapping the values from `read.table` like: `str(all_pval)` and `str(all_means)` could help.

**Comment by yjgeno** [comment]
Thanks, the latter works!
