### ISSUE TITLE
strict requirements

### ISSUE THREAD

**Issue by igordot** [Teichlab/cellphonedb#333]
Are there any plans to relax or update the requirements? Most of the packages have a maximum version that is several releases earlier than the current version. For example, the latest acceptable version of `tqdm` is over 2 years old. It is becoming increasingly difficult to install any other tools in the same environment. There was a previous pull request that addressed this issue (https://github.com/Teichlab/cellphonedb/pull/232).

**Comment by prete** [comment]
Hi @igordot thank you for using CellPhoneDB. We're looking at which ones we can uncap and which ones need a strict version for the next release coming up soon. Hopefully that will solve this annoyance.

PR #232 didn't fix that because some versions have breaking changes for us (particularly numpy/pandas). Others have minor but annoying differences (ie click) or require extensive testing afterwards to make sure the results are still the same (like scikit-learn/geosketch). Simply removing the maximum versions is not a valid solution, we need to be careful when updating dependencies.

**Comment by igordot** [comment]
I understand it's difficult to resolve all the inconsistencies. I mostly just wanted to check if this was on your radar. Any progress would be appreciated.

**Comment by prete** [comment]
Requirements shouldn't be an issue in the latest version: https://github.com/ventolab/CellphoneDB
