### ISSUE TITLE
count_network

### ISSUE THREAD

**Issue by cadyyuheng** [Teichlab/cellphonedb#340]
Hello,

I'm wondering if we could get more description on how the count_network.txt file is generated, especially how it is defined. Thanks!

**Comment by prete** [comment]
Hi @cadyyuheng `count_network.txt` is generated by this R script: https://github.com/Teichlab/cellphonedb/blob/master/cellphonedb/src/plotters/R/plot_heatmaps.R

The chunk that generates the file counts the **total number of interactions between two clusters**. The headers (`'SOURCE','TARGET','count/`) may be a bit misleading because the file will have the same count for cluster `A|B` than for `B|A`, it counts total interactions an not just directional ones. That being said, it's useful to quickly see which clusters interact the most with each other.

**Comment by cadyyuheng** [comment]
@prete , thanks so much for the clarification -- It definitely makes more sense for me now!
